mysite/mainapp/urls.py
from . import views
from django.urls import path

app_name = 'mainapp'
urlpatterns = [
    path('gift-list', views.index, name='index'),
    path('recipients', views.distinct_recipients, name='recipients'),
    path('gift-details/<int:id>', views.details, name='details'),
    path('add-new-gift', views.create_item, name='create_item'),
    path('update-gift/<int:id>', views.update_item, name='update_item'),
    path('delete-gift/<int:id>', views.delete_item, name='delete_item'),
    path('page-does-not-exist', views.page_does_not_exist, name='no_page'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from Users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('register', user_views.register, name='Register'),
    path('login', auth_views.LoginView.as_view(
        template_name='Users/login.html'), name='Login'),
    path('logout', auth_views.LogoutView.as_view(
        template_name='Users/logout.html'), name='Logout'),
    #path('profile', user_views.profilepage, name='Profile'),
]


urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/mainapp/models.py
from django.db import models

# Create your models here.


class Recipient(models.Model):
    def __str__(self):
        return self.name

    name = models.CharField(max_length=150)
    user = models.ForeignKey(
        "auth.User",
        on_delete=models.CASCADE
    )


class gift(models.Model):
    def __str__(self):
        return self.gift_name

    gift_name = models.CharField(max_length=150)
    price = models.FloatField()
    type = models.CharField(max_length=150)
    recipient = models.ForeignKey(Recipient, on_delete=models.CASCADE)
    user = models.ForeignKey(
        "auth.User",
        on_delete=models.CASCADE,
    )
    year = models.IntegerField()

mysite/mainapp/forms.py
from urllib import request
from django.forms import TextInput, Select
from django import forms
from .models import gift, Recipient


class RecipientForm(forms.ModelForm):
    class Meta:
        model = Recipient
        fields = ['name']
        widgets = {
            'name': TextInput(attrs={
                'class': "form-control",
                'style': 'width: 30rem;',
                'placeholder': 'Recipient\'s name',
            })
        }


class ItemForm(forms.ModelForm):
    class Meta:
        model = gift
        fields = ['recipient', 'gift_name', 'price', 'type', 'year']
        widgets = {
            'recipient': Select(attrs={
                'class': "form-control",
                'style': 'width: 30rem;',
                'placeholder': 'Recipient'
            }),
            'gift_name': TextInput(attrs={
                'class': "form-control",
                'style': 'width: 30rem;',
                'placeholder': 'Gift name'
            }),
            'price': TextInput(attrs={
                'class': "form-control",
                'style': 'width: 30rem;',
                'placeholder': 'Price'
            }),
            'type': TextInput(attrs={
                'class': "form-control",
                'style': 'width: 30rem;',
                'placeholder': 'Short Description'
            }),
            'year': TextInput(attrs={
                'class': "form-control",
                'style': 'width: 30rem;',
                'placeholder': 'Year'
            }),
        }

    # I used ChatGPT to help solve the issue of filtering the select options based on the user that is logged in
    # This code was generated by ChatGPT, super cool.
    def __init__(self, *args, **kwargs):
        # Get the request object from the keyword arguments
        request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

        # Filter the queryset for the recipient field by user
        if request:
            self.fields['recipient'].queryset = Recipient.objects.filter(
                user=request.user)

mysite/mainapp/views.py
from django.shortcuts import render, redirect
from .models import gift as Gift, Recipient
from .forms import ItemForm, RecipientForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.contrib import messages

# Create your views here.


def index(request):
    gift_list = Gift.objects.filter(
        user=request.user.id)
    paginator = Paginator(gift_list, 8)
    page = request.GET.get('page')
    gift_list = paginator.get_page(page)
    context = {
        'gift_list': gift_list
    }
    return render(request, 'mainapp/index.html', context)


def distinct_recipients(request):
    recipients = Recipient.objects.filter(user=request.user.id)
    context = {'recipients': recipients}
    return render(request, 'mainapp/recipients.html', context)


@login_required
def details(request, id):
    try:
        item = Gift.objects.get(pk=id)
        context = {'item': item}

        return render(request, "mainapp/details.html", context)
    except Gift.DoesNotExist:
        return redirect('mainapp:no_page')


@login_required
def create_item(request):
    form = ItemForm(request.POST or None, request=request)
    recipient = RecipientForm(request.POST or None)

    if form.is_valid():
        profile = form.save(commit=False)
        profile.user = request.user
        profile.save()
        if 'submit-create-item' in request.POST:
            messages.success(
                request, f'{profile} added successfully')
            return redirect('mainapp:create_item')
        return redirect('mainapp:index')

    elif recipient.is_valid():
        rec = recipient.save(commit=False)
        rec.user = request.user
        rec.save()
        messages.success(
            request, f'{rec} added successfully')
        return redirect('mainapp:create_item')

    return render(request, "mainapp/item-form.html", {'form': form, 'recipient': recipient})


@login_required
def update_item(request, id):
    try:
        item = Gift.objects.get(id=id)
    except Gift.DoesNotExist:
        return redirect('mainapp:no_page')

    form = ItemForm(request.POST or None, instance=item, request=request)
    if form.is_valid():
        form.save()
        return redirect('mainapp:index')

    return render(request, "mainapp/item-update.html", {'form': form, 'item': item})


@login_required
def delete_item(request, id):
    try:
        item = Gift.objects.get(id=id)
    except Gift.DoesNotExist:
        return redirect('mainapp:no_page')

    if request.method == 'POST':
        item.delete()
        return redirect('mainapp:index')

    return render(request, "mainapp/item-delete.html", {'item': item})


def page_does_not_exist(request):
    return render(request, "mainapp/doesnotexist.html")

mysite/mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Santa's Bag</title>
    <!-- CSS only -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'mainapp/style.css' %}">
    <link href="https://fonts.cdnfonts.com/css/holiday" rel="stylesheet">
                
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="{% static 'mainapp/script.js' %}"></script>

    
</head>

<body style="height: 100%;" alt="Background image: White Snowy Environment With Pine Trees">
<nav class="navbar navbar-light">
    
    <a href=
    {% if user.is_authenticated %}
        "{% url 'mainapp:index' %}"
    {% else %} 
        "{% url 'Login' %}" 
    {% endif %} 
    class="navbar-brand holiday-font ml-5" style="font-size: 2.2rem;">
        <img src="/pictures/christmas-gift-icon.svg" width="60" height="60" alt="">
        <span class="align-bottom" id="navbar-brand-text"></span>
    </a>
   
    <div class="navbar" style="margin-right: 5rem">
        <div class="d-flex pr-5">
            <div class='block-container countdown-header'>
                <div class'pr-2 '>
                    <p class="m-0 text-center font-italic font-weight-bold">Christmas Countdown</p>
                </div>

                <div class='container p-0 countdown-time font-weight-bold'>
                    <div class='pr-2'>
                        <p id="days" class='text-center m-0'>Days</p>
                        <p class="text-center m-0">Days</p>
                    </div>

                    <div class='pr-2'>
                        <p id="hours" class='text-center m-0'></p>
                        <p class='text-center m-0'>Hours</p>
                    </div>

                    <div class='pr-2'>
                        <p id="minutes" class='text-center m-0'></p>
                        <p class='text-center m-0'>Mins</p>
                    </div>

                    <div class='pr-2'>
                        <p id="seconds" class='text-center m-0'></p>
                        <p class='text-center m-0'>Secs</p>
                    </div>
                </div>
            </div>
        </div>

        {% if user.is_authenticated %} 
        <a href="{% url 'mainapp:create_item' %}" class="mr-3 btn btn-outline-success nav-item nav-link">Add Gift</a>
        <a href = "{% url 'Logout' %}" class="btn btn-outline-success nav-item nav-link">Logout</a>
        {% else %}
        <a href = "{% url 'Login' %}" class="mr-3 btn btn-outline-success nav-item nav-link">Login</a>
        <a href = "{% url 'Register' %}" class="btn btn-outline-success nav-item nav-link">Sign Up</a>
        {% endif %}
    </div>
</nav>   

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-dismissible alert-{{ message.tags }}">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <h4 class='text-center m-0'>{{ message }}</h4>
        </div>
    {% endfor %}
{% endif %} 

{% block body %} 
{% endblock %}

{% if request.path == '/login' %}
    <script>              
        addClassToNav('nav-login','nav')
        changeAltText('body', 'Background image: Wrapped Gift Boxes With Ribbons on Table.')
    </script>
{% endif %}
<script>
    updateCountdown()
    letterColorChange("Santa's Bag")
</script>

<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>   
</body>

</html>

mysite/mainapp/templates/mainapp/details.html
{% extends 'mainapp/base.html'%}
{% block body %}

{% if  item.user == user %} <!--Make sure only the correct user is able to see details-->
    <div class="container-fluid"> 
        <div class="mt-3 d-flex justify-content-center flex-nowrap">
            <div style='background: rgba(0, 255, 0, 0.25); width: 35rem' class ="mt-5 rounded p-5 neu-shadow">
            <div class="card background-color-card border-0">
            <div class="col card-body">
                <h1 class="card-title text-center holiday-font pb-1">{{item.gift_name|capfirst}}</h1>
                <h2>${{item.price}}</h2>
                <h3>Short Description: <br>{{item.type}}</h3>
                <h3>For: {{item.recipient|capfirst}}</h3>
                <h3>Year: {{item.year}}</h3>
                <div class="d-flex justify-content-between pt-2">
                    <a href="{% url 'mainapp:update_item' item.id %}" class="mt-3 btn btn-outline-primary col-6">Edit</a>
                    <a href="{% url 'mainapp:delete_item' item.id %}" class="mt-3 btn btn-outline-danger col-4">Delete</a>
                </div>
            </div>
            </div>
            </div>
        </div>
    </div>
{% else %}
    <p>Oops! No peaking at other's presents. <a href="{% url 'mainapp:index' %}">Click here to return to your gift bag</a></p>
{% endif %}

{% endblock %}

mysite/mainapp/templates/mainapp/doesnotexist.html
{% extends 'mainapp/base.html'%}
{%block body%}
<div class='container-fluid mt-5 d-flex justify-content-center'>
    <div class='block'>
        <h1 style='color: red;' class="mt-5 holiday-font text-center" >That page does not exist</h1>
    </div>
</div>
{%endblock%}

mysite/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
    {% block body %}
    
    <div class="container-fluid col-8"> 
        <div class="row justify-content-center">
        {% if not gift_list %}
            <div class='container-fluid border p-5 neu-shadow mt-5 d-flex justify-content-center custom-width'>
                <div class=''>
                    <h1 style='color: red;' class="text-center col-12 mt-5 holiday-font text-center" >Welcome to Santa's Bag, {{user.username}}!</h1>
                    <h2 style='color: dodgerblue;' class="text-center col-12 mt-5 holiday-font text-center" >You haven't added any gifts to your bag yet. Please Select the button below to add your first gift: </h2>
                    <a href="{% url 'mainapp:create_item' %}" class="mt-5 col-12 btn btn-outline-success">Add Gift</a>
                </div>
            </div>
        {% else %}
            {% for item in gift_list %}
            <div class="mt-5 col d-flex align-items-stretch custom-margin-btn">
                <div class="card mx-auto background-color-card border-0 align-items-center" style="width: 15rem;">
                    <img class="card-img-top" src="pictures/red-ribbon.png" alt="There is a red bow on top of the card with gift name and recipient name info, making it look more like a present than just a card with some info." style="width:8rem; margin-bottom: -42px;">
                    <div class="card mx-auto neu-shadow" style="width: 15rem;">
                        <div class="card-body text-center d-flex flex-column reg-img">
                            <h4 class= "card-title">{{ item.gift_name|capfirst }}</h4>
                            <h5 class="card-body">for {{ item.recipient|capfirst }}</h5>
                            <a href="{% url 'mainapp:details' item.id %}" class="btn neu-shadow-inset">Details</a>                    
                        </div>
                    </div>
                </div>
            </div>               
            {% endfor %}

            
            {% endif %}
        </div>   
        <nav>
            <ul class="pagination justify-content-center mt-5">
              {% if gift_list.has_previous %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ gift_list.previous_page_number }}">&laquo;</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1" aria-disabled="True">&laquo;</a>
                </li>
              {% endif %}
              {% for i in gift_list.paginator.page_range %}
                {% if gift_list.number == i %}
                  <li class="page-item active" aria-current="page">
                    <span class="page-link">
                      {{ i }}
                      <span class="sr-only">(current)</span>
                    </span>
                  </li>
                {% else %}
                  <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
              {% endfor %}
              {% if gift_list.has_next %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ gift_list.next_page_number }}">&raquo;</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1" aria-disabled="True">&raquo;</a>
                </li>
              {% endif %}
            </ul>
          </nav>
    </div>   
    {% endblock %}

mysite/mainapp/templates/mainapp/item-delete.html
{% extends 'mainapp/base.html'%}
{%block body%}
<div class='container-fluid mt-5 d-flex justify-content-center'>
    <form method="post">
        {% csrf_token %}
        <div class='block'>
            <h2 class='mt-5'>Are you sure you want to delete this gift?</h2>
            <button type="submit" class="mt-5 col-12 btn btn-outline-danger">Confirm</button>
        </div>
    </form>
</div>  
{% endblock %}

mysite/mainapp/templates/mainapp/item-form.html
{% extends 'mainapp/base.html'%}
{%block body%}
<div class="container-fluid"> 
    <div class="mt-3 d-flex justify-content-center flex-nowrap">
        <div style='background: rgba(197, 7, 0, 0.25);' class ="mt-5 border-0 neu-shadow rounded p-5">
            <h1 class="holiday-font text-center text-black">Add Gift</h2>
            <form method="POST">
                {% csrf_token %}
                    <div class="form-group">
                        {{form.recipient}}
                    </div>
                    <div class="form-group"> 
                        {{form.gift_name}}
                    </div>
                    <div class="form-group">  
                        {{form.price}}
                    </div>
                    <div class="form-group"> 
                        {{form.type}}
                    </div>
                    <div class="form-group"> 
                        {{form.year}}
                    </div>
                <div class="form-group d-flex justify-content-between"> 
                    <button type="submit" name="submit and go to gift list" class="btn btn-outline-primary col-5">Save</button>
                    <button type="submit" name = "submit-create-item" class="btn btn-outline-primary col-6">Save and Add Another</button>
                </div>
            </form>
            <h3 class="mt-5 holiday-font text-center text-black">Add Recipient</h3>
            <p class="" style='max-width: 30rem'>Nobody in the dropdown above? No worries, you can add people here:</p>
            <form method="POST">
                {% csrf_token %}                
                <div class="form-group"> 
                    {{recipient.name}}  
                </div>                   
                
                <div class="form-group">    
                    <button type="submit" class="btn btn-outline-primary col-12">Add Person</button>
                </div>
            </form>
        </div>
    </div>
</div>
</div>

</div>
</div>
{%endblock%}

mysite/mainapp/templates/mainapp/item-update.html
{% extends 'mainapp/base.html'%}
{%block body%}
<div class="mt-5 d-flex justify-content-center flex-nowrap">
    <div class ="mt-5 border-0 rounded p-5 bg-image update-img neu-shadow" alt="Closeup of Christmas tree with red and sparkling gold ornament.">
        <h1 class="holiday-font text-center text-white">Update Gift</h2>
            <form method="POST">
                {% csrf_token %}
                    <div class="form-group"> 
                        {{form.recipient}}
                    </div>
                    <div class="form-group"> 
                        {{form.gift_name}}
                    </div>
                    <div class="form-group"> 
                        {{form.price}}
                    </div>                
                    <div class="form-group"> 
                            {{form.type}}
                    </div>                
                    <div class="form-group"> 
                        {{form.year}}
                    </div>            
                    <div class="form-group"> 
                        <button type="submit" class="btn col-12 btn-outline-primary">Update Gift</button>
                    </div>
            </form>
        </div>
    </div>
</div>
{%endblock%}

mysite/mainapp/templates/mainapp/recipients.html
{% extends 'mainapp/base.html'%}
{%block body%}
{% if user.is_authenticated %} 
    {% for item in recipients  %}
        <h1>{{item}}</h1>
    {% endfor %}
{% endif %}
{%endblock%}