mysite/mainapp/urls.py
from . import views
from django.urls import path

app_name = 'mainapp'
urlpatterns = [
    path('gift-list', views.index, name='index'),
    path('recipients', views.distinct_recipients, name='recipients'),
    path('gift-details/<int:id>', views.details, name='details'),
    path('add-new-gift', views.create_item, name='create_item'),
    path('update-gift/<int:id>', views.update_item, name='update_item'),
    path('delete-gift/<int:id>', views.delete_item, name='delete_item'),
    path('page-does-not-exist', views.page_does_not_exist, name='no_page'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from Users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('register', user_views.register, name='Register'),
    path('login', auth_views.LoginView.as_view(
        template_name='Users/login.html'), name='Login'),
    path('logout', auth_views.LogoutView.as_view(
        template_name='Users/logout.html'), name='Logout'),
    #path('profile', user_views.profilepage, name='Profile'),
]


urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/Users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg',
                              upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

mysite/Users/forms.py
from django import forms
from django.forms import TextInput
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


# class LoginForm(UserCreationForm):
#     password = forms.CharField(widget=forms.PasswordInput(attrs={
#         'class': "form-control",
#         'style': 'max-width: 25rem;',
#         'placeholder': 'Password'}))

#     class Meta:
#         model = User
#         fields = ['username', 'password']
#         widgets = {
#             'username': TextInput(attrs={
#                 'class': "form-control",
#                 'style': 'max-width: 25rem;',
#                 'placeholder': 'Username'
#             }),
#         }


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': "form-control",
        'style': 'width: 30rem;',
        'placeholder': 'Email'}))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': "form-control",
        'style': 'width: 30rem;',
        'placeholder': 'Password'}))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': "form-control",
        'style': 'width: 30rem;',
        'placeholder': 'Confirm Password'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            'username': TextInput(attrs={
                'class': "form-control",
                'style': 'width: 30rem;',
                'placeholder': 'Username'
            }),
        }

mysite/Users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import RegistrationForm
from django.contrib.auth.decorators import login_required

# Create your views here.


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(
                request, f'Welcome {username}! Account created successfully.')
            return redirect('Login')
    else:
        form = RegistrationForm()
    return render(request, 'Users/register.html', {'form': form})


@login_required
def profilepage(request):
    return render(request, 'Users/profile.html')

mysite/Users/templates/Users/login.html
{% extends 'mainapp/base.html'%}
{%block body%}
{% if user.is_authenticated %} 
<div class='container-fluid mt-5 d-flex justify-content-center'>
    <div class='block'>
        <p>You are already logged in.</p>
        <div class='d-flex justify-content-between'>
            <a href = "{% url 'mainapp:index' %}" class="col-5 btn btn-outline-primary">Home</a>
            <a href = "{% url 'Logout' %}" class="col-5 btn btn-outline-warning">Logout</a>
        </div>
    </div>
</div>
{% else %}
<div class='container-fluid'>
    
    <div class="d-flex justify-content-center flex-nowrap">
        <form style='background: rgba(197, 7, 0, .5); margin-top: 12rem;'class="rounded p-5" method="POST">
            <h1 class="text-center text-white font-weight-bold holiday-font">Yule Log In</h1>
            {%csrf_token%} 
            <div class="form-group">
                {{form.errors}}
                  <input class="form-control" type="text" placeholder="Username" name="username" style="width:25rem" id="id_username">
                </div>        
                
                <div class="form-group">
                    <input class="form-control" type="password" style="width:25rem" name="password" placeholder='Password' id="id_password">
                </div>        
                <div class="d-flex justify-content-between">
                    <button type="submit" class="btn btn-outline-success col-7 font-weight-bold">Login</button>
                    <a href = "{% url 'Register' %}" class="btn btn-outline-secondary col-3 font-weight-bold">Sign Up</a>
                </div>
            </form>
        </div>        
        
    </div>        
    {% endif %}
    <style>
        body {
            background-image: url('/pictures/presents.jpeg'); 
        }
    </style>
    {%endblock%}

mysite/Users/templates/Users/logout.html
{% extends 'mainapp/base.html'%}
{%block body%}
<div class='container-fluid mt-5 d-flex justify-content-center'>
    <div class='block'>
        <h1 style='color: black;' class="mt-5 holiday-font text-center" >Yule Logged Out</h1>
        <p style='color: black; font-size: 2rem;' class=" holiday-font text-center">Happy Holidays!</p>
    </div>
</div>
{%endblock%}

mysite/Users/templates/Users/profile.html
{% extends 'mainapp/base.html'%}
{%block body%}
<h1>{{user.username}}</h1>
<img src="{{user.profile.image.url}}" alt="profile image" width="300rem">
{%endblock%}

mysite/Users/templates/Users/register.html
{% extends 'mainapp/base.html'%}
{%block body%}
<div class="container-fluid"> 
    <div class="mt-5 d-flex justify-content-center flex-nowrap">
        <div class ="mt-5 border rounded p-5 bg-image reg-img">
            <h1 class="holiday-font text-center text-white">Sign Up</h2>
            <form class="" method="POST">
                {%csrf_token%}
                {% for field in form  %}
                    <div class="form-group">
                        {{field.errors}}     
                        {{field}}        
                    </div>
                {% endfor %}
                

                <button type="submit" class="btn btn-outline-primary col-12">Register</button>
            </form>
        </div>
    </div>
</div>
{%endblock%}